siteTitle = "Fuck Up Some Comics"
siteDescr = "Fuck up some comics, yeah."
siteAuthor = "Foggy"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = ""