siteTitle = "Fuck Up Some Comics"
siteDescr = "Fuck up some comics, yeah."
siteAuthor = "Foggy"

siteTelegramUrl = "#"
siteTwitterUrl = "https://www.twitter.com/austinlanari"
siteGithubUrl = "https://www.github.com/foggy1"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-80918633-2"

linkPrefix = ""